services:
  server:
    build: ./server
    image: ghcr.io/monishramj/campout-server:latest
    volumes:
      - campout_socket:/tmp
    networks:
      - campout_net
  gateway:
    build: 
      context: .
      dockerfile: gateway/dockerfile
    image: ghcr.io/monishramj/campout-gateway:latest
    depends_on: 
      - server
    ports:
      - 8000:8000
    volumes:
      - campout_socket:/tmp
    networks:
      - campout_net
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=val
      - POSTGRES_PASSWORD=val
      - POSTGRES_DB=val
    networks:
      - campout_net
volumes:
  campout_socket:
networks:
  campout_net:
    driver: bridge