FROM python:3.12-slim 

WORKDIR /app

COPY gateway/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY gateway/ /app/
COPY client /client/

# compose will publish, keep in mind
EXPOSE 8000

CMD ["uvicorn", "main:app", "--port", "8000", "--host", "0.0.0.0"]